name: CI

on: [push, pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: run test
        run: npm test --watchAll=false --coverage
